/*
 * Copyright 2015 eBay Software Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eu.recred.fidouaf.tlv;

public enum TagsEnum {
	
	UAF_CMD_STATUS_OK(0x00),
	UAF_CMD_STATUS_ERR_UNKNOWN (0x01),
	UAF_CMD_STATUS_ACCESS_DENIED(0x02),
	UAF_CMD_STATUS_USER_NOT_ENROLED(0x03),
	UAF_CMD_STATUS_CANNOT_RENDER_TRANSACTION_CONTENT(0x04),
	UAF_CMD_STATUS_USER_CANCELED(0x05),
	UAF_CMD_STATUS_CMD_NOT_SUPPORTED(0x06),
	UAF_CMD_STATUS_ATTESTATION_NOT_SUPPORTED(0x06),
	TAG_UAFV1_REG_ASSERTION(0x3E01),
	TAG_UAFV1_AUTH_ASSERTION(0x3E02),
	TAG_UAFV1_KRD(0x3E03),
	TAG_UAFV1_SIGNED_DATA(0x3E04),
	TAG_ATTESTATION_CERT(0x2E05),
	TAG_SIGNATURE(0x2E06),
	TAG_ATTESTATION_BASIC_FULL(0x3E07),
	TAG_ATTESTATION_BASIC_SURROGATE(0x3E08),
	TAG_KEYID(0x2E09),
	TAG_FINAL_CHALLENGE(0x2E0A),
	TAG_AAID(0x2E0B),
	TAG_PUB_KEY(0x2E0C),
	TAG_COUNTERS(0x2E0D),
	TAG_ASSERTION_INFO(0x2E0E),
	TAG_AUTHENTICATOR_NONCE(0x2E0F),
	TAG_TRANSACTION_CONTENT_HASH(0x2E10),
	TAG_EXTENSION(0x3E11),
	TAG_EXTENSION_NON_CRITICAL(0x3E12),
	TAG_EXTENSION_ID(0x2E13),
	TAG_EXTENSION_DATA(0x2E14),
	TAG_UAFV1_GETINFO_CMD(0x3401),
	TAG_UAFV1_GETINFO_CMD_RESPONSE(0x3601),
	TAG_UAFV1_REGISTER_CMD(0x3402),
	TAG_UAFV1_REGISTER_CMD_RESPONSE(0x3602),
	TAG_UAFV1_SIGN_CMD(0x3403),
	TAG_UAFV1_SIGN_CMD_RESPONSE(0x3603),
	TAG_UAFV1_DEREGISTER_CMD(0x3404),
	TAG_UAFV1_DEREGISTER_CMD_RESPONSE(0x3606),
	TAG_UAFV1_OPEN_SETTINGS_CMD(0x3406),
	TAG_UAFV1_OPEN_SETTINGS_CMD_RESPONSE(0x3606),
	TAG_KEYHANDLE(0x2801),
	TAG_USERNAME_AND_KEYHANDLE(0x3802),
	TAG_USERVERIFY_TOKEN(0x2803),
	TAG_APPID(0x2804),
	TAG_KEYHANDLE_ACCESS_TOKEN(0x2805),
	TAG_USERNAME(0x2806),
	TAG_ATTESTATION_TYPE(0x2807),
	TAG_STATUS_CODE(0x2808),
	TAG_AUTHENTICATOR_METADATA(0x2809),
	TAG_ASSERTION_SCHEME(0x280A),
	TAG_TC_DISPLAY_CONTENT_TYPE(0x280C),
	TAG_AUTHENTICATOR_INDEX(0x280D),
	TAG_API_VERSION(0x280E),
	TAG_AUTHENTICATOR_ASSERTION(0x280F),
	TAG_TRANSACTION_CONTENT(0x2810),
	TAG_AUTHENTICATOR_INFO(0x3811),
	TAG_SUPPORTED_EXTENSION_ID(0x2812);
	
	final public int id;

	TagsEnum (int id){
		this.id = id;
	}
	
	public static TagsEnum get(int id){
		for (TagsEnum tag : TagsEnum.values()) {
			if (tag.id == id){
				return tag;
			}
		}
		return null;
	}
}
